INSERT INTO tabby.category (id, name, subcategory) VALUES
(uuidv7(), 'Entertainment', 'Games'),
(uuidv7(), 'Entertainment', 'Movies'),
(uuidv7(), 'Entertainment', 'Music'),
(uuidv7(), 'Entertainment', 'Other'),
(uuidv7(), 'Entertainment', 'Sports'),
(uuidv7(), 'Food and drink', 'Dining out'),
(uuidv7(), 'Food and drink', 'Groceries'),
(uuidv7(), 'Food and drink', 'Liquor'),
(uuidv7(), 'Food and drink', 'Other'),
(uuidv7(), 'Home', 'Electronics'),
(uuidv7(), 'Home', 'Furniture'),
(uuidv7(), 'Home', 'Household supplies'),
(uuidv7(), 'Home', 'Maintenance'),
(uuidv7(), 'Home', 'Mortgage'),
(uuidv7(), 'Home', 'Other'),
(uuidv7(), 'Home', 'Pets'),
(uuidv7(), 'Home', 'Rent'),
(uuidv7(), 'Home', 'Services'),
(uuidv7(), 'Life', 'Childcare'),
(uuidv7(), 'Life', 'Clothing'),
(uuidv7(), 'Life', 'Education'),
(uuidv7(), 'Life', 'Gifts'),
(uuidv7(), 'Life', 'Insurance'),
(uuidv7(), 'Life', 'Medical expenses'),
(uuidv7(), 'Life', 'Other'),
(uuidv7(), 'Life', 'Taxes'),
(uuidv7(), 'Transportation', 'Bicycle'),
(uuidv7(), 'Transportation', 'Bus/train'),
(uuidv7(), 'Transportation', 'Car'),
(uuidv7(), 'Transportation', 'Gas/fuel'),
(uuidv7(), 'Transportation', 'Hotel'),
(uuidv7(), 'Transportation', 'Other'),
(uuidv7(), 'Transportation', 'Parking'),
(uuidv7(), 'Transportation', 'Plane'),
(uuidv7(), 'Transportation', 'Taxi'),
(uuidv7(), 'Uncategorized', 'General'),
(uuidv7(), 'Utilities', 'Cleaning'),
(uuidv7(), 'Utilities', 'Electricity'),
(uuidv7(), 'Utilities', 'Heat/gas'),
(uuidv7(), 'Utilities', 'Other'),
(uuidv7(), 'Utilities', 'Trash'),
(uuidv7(), 'Utilities', 'TV/Phone/Internet'),
(uuidv7(), 'Utilities', 'Water');